---
id: oso2013
base_name: android-annotations
tags: []
presentation_date: 2013/05/11
version: 2013.05.11
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :markdown
  name: ryosms
  email: 
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
